# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
    ]
