# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170730_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plege',
            name='percentage',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
