# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20170730_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plege',
            new_name='Pledge',
        ),
    ]
